GradientBoostingClassifier:
  n_estimators: 89 # Number of boosting stages
  learning_rate: 0.4 # Step size shrinkage
  max_depth: 4 # Maximum depth of the individual trees
  min_samples_split: 2 # Minimum number of samples required to split an internal node
  min_samples_leaf: 2 # Minimum number of samples required to be at a leaf node
  subsample: 0.8 # Fraction of samples to be used for fitting the individual base learners
  random_state: 42
