artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: artifacts/test/stb_data.csv
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_cleaning:
  root_dir: artifacts/data_cleaning
  data_path: artifacts/data_ingestion/data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_cleaning/clean_data.csv

data_training:
  root_dir: artifacts/data_training
  data_path: artifacts/data_transformation/transforming_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_training/train.csv
  test_data_path: artifacts/data_training/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_training/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
