artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: C:/Users/Lenovo/Desktop/pfe_project/jupyter_model/stb_data.csv
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion



